### ISSUE TITLE
Investigate `devise-security` gem

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#1460]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

The `devise-security` gem has some extra security stuff we could take advantage of. I'm thinking specifically of `:session_limitable` and possibly `:paranoid_verification` and maybe an out of the box `:expirable` to replace the custom code we have now.

* **What feature or behavior is this required for?**

An additional layer of authentication security.

* **How could we solve this issue? (Not knowing is okay!)**

Investigate the gem and whether or not it works with mongoid; if so, install, if not go ahead and close.

* **Anything else?**

https://github.com/devise-security/devise-security

Recommended but not necessary by our sec audit.

**Comment by tingaloo** [comment]
From the readme. 
```Note: Unlike Devise, devise-security does not currently support mongoid. Pull requests are welcome!```

There's a [WIP pr](
https://github.com/devise-security/devise-security/pull/43)

**Comment by colinxfleming** [comment]
Mongoid support got merged! https://github.com/devise-security/devise-security/pull/76

**Comment by colinxfleming** [comment]
Let's do:
* password_archivable
* session_limitable

we already have expiration set up and trust it, our password posture is fine, and paranoid_verification is something we'd need to do more thoughtfully.

**Comment by colinxfleming** [comment]
declaring victory on here, I think @djohnston32 got the ones that are appropriate for us
