### ISSUE TITLE
Slap an additional cloud based app firewall up

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#1462]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

Several major cloud service providers offer free DDoS protection/web application firewalls to non-profit organizations. We have rack-attack which saves us from this in the small scale, but big corporations have more security firepower than we ever will, so we can and should take advantage of their services too.

* **What feature or behavior is this required for?**

Preventing jerks from blowing up the world

* **How could we solve this issue? (Not knowing is okay!)**

Pick your fave/whatever requires the least paperwork:

​https://deflect.ca/
​https://www.cloudflare.com/galileo/
https://projectshield.withgoogle.com/public/

* **Anything else?**

Make sure this is something that heroku doesn't handle for us automatically!

**Comment by colinxfleming** [comment]
(project shield fairly easy to apply for and we should do it after we have 501c status)

**Comment by colinxfleming** [comment]
was going through old tickets and found this. I'm going to apply for project galileo since we're already cloudflare babies and see what happens.

**Comment by colinxfleming** [comment]
we got onto project galileo! I think the next step here is to set up anything fresh that we have access to thru cloudflare and then declare victory.

**Comment by xmunoz** [comment]
Now that we are on Cloudflare, we get DDoS protection for free.

As for a WAF, we have that turned on with [a managed ruleset](https://dash.cloudflare.com/04a3c6a398793e6f59a1dbcadcd9ddc9/dariaservices.com/security/waf/managed-rules).

I'll look into what else might be available through Galileo.

**Comment by xmunoz** [comment]
We can enable the [Cloudflare OWASP Core Ruleset](https://developers.cloudflare.com/waf/managed-rules/reference/owasp-core-ruleset/) as well, but looking at the security analytics, we aren't getting a bunch of spammy/bot traffic to the site.

**Comment by xmunoz** [comment]
I've enabled [DNSSEC](https://www.cloudflare.com/dns/dnssec/how-dnssec-works/) for dariaservices.com and dariaservices.org.
