### ISSUE TITLE
Restore yarn audit after webpacker 4 gets fixed

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#1665]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

Webpacker 4 uses an insecure JS library, js-yaml. Until it gets a new release it's triggering yarn audit in CI and failing builds. This is a ticket to bump the gem, redo the yarn install, and turn `yarn audit` back on.

* **What feature or behavior is this required for?**

security

* **How could we solve this issue? (Not knowing is okay!)**

* bump webpacker gem
* reinstall yarn packages, including a fixed version of js-yaml
* turn yarn audit back on in CI

* **Anything else?**

nah

**Comment by rudietuesdays** [comment]
ambitiously planning to tackle this tonight as well!

**Comment by colinxfleming** [comment]
this might be live again! webpacker is on 4.0.7 now so this is probably boopable, hopefully?

**Comment by lomky** [comment]
Let's give this a shot again maybe? :eyes:
