### ISSUE TITLE
Spanish: Translate Multimodal Buttons

### ISSUE THREAD

**Issue by lomky** [DARIAEngineering/dcaf_case_management#1670]
Cancel/Ok buttons and the Cancel/Next/Complete on Pledge gen need to be translated to Spanish.

> The cancel/ok button is a particularly hard one since we've rarely touched the multimodal since setting it up, and I don't think the text on a few buttons should hold up a more general launch. (though maybe @montanezp would disagree.) 
> 
> _Originally posted by @colinxfleming in https://github.com/DCAFEngineering/dcaf_case_management/issues/1648#issuecomment-471240611_

**Comment by colinxfleming** [comment]
low reward on this so closing
