### ISSUE TITLE
Spanish Bug: Locale setting sometimes lost on Login / Logout 

### ISSUE THREAD

**Issue by lomky** [DARIAEngineering/dcaf_case_management#1671]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

Sometimes the app swaps back to English when you log in or log out. The log out isn't such a big problem, but it's annoying to swap the app to Spanish twice.

* **What feature or behavior is this required for?**

Better Spanish mode!

* **How could we solve this issue? (Not knowing is okay!)**

Not the slightest.

Originally discovered in #1648

**Comment by colinxfleming** [comment]
low reward to fixing this, closing
