### ISSUE TITLE
JS: Port external_pledges.coffee from coffeescript to ES6

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#1682]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

We're porting our custom javascript to ES6! This ticket is to port over:

external_pledges.coffee into app/javascript/src/pledge_modal.js

* **What feature or behavior is this required for?**

Long term project health and maintainability, plus an opportunity to clean up some of our messes when we wrote this the first time.

* **How could we solve this issue? (Not knowing is okay!)**

Rewrite the coffeescript in app/assets/ to be ES6 in app/javascript/src.

* **Anything else?**

See #1679 for an example of this with the `clinic_finders` js.

If this winds up requiring adding dependencies or something, please hit me up in slack!

**Comment by jmhooper** [comment]
Looking at this one :eyes:

**Comment by colinxfleming** [comment]
@jmhooper still on this one?

**Comment by jmhooper** [comment]
Yep!

**Comment by colinxfleming** [comment]
`modalSteps()` depends on a vendored library which isn't on npm, and which hasn't been touched in several years. We should either re-vendor it in webpack or kill it dead and replace it with something else, but this file is fine to hang out in sprockets for now.

**Comment by colinxfleming** [comment]
this is solved as part of our nuking webpack
