### ISSUE TITLE
JS: Port over autosave part of patients.coffee from coffeescript to ES6

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#1686]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

We're porting our custom javascript to ES6! This ticket is to port over:

L57-58 and L65-66 of patients.coffee into app/src/javascript/autosave.js

* **What feature or behavior is this required for?**

Long term project health and maintainability, plus an opportunity to clean up some of our messes when we wrote this the first time.

* **How could we solve this issue? (Not knowing is okay!)**

Rewrite the coffeescript in app/assets/ to be ES6 in app/javascript/src.

* **Anything else?**

See #1679 for an example of this with the `clinic_finders` js.

If this winds up requiring adding dependencies or something, please hit me up in slack!

**Comment by bravogolfgolf** [comment]
I got this one.

**Comment by colinxfleming** [comment]
Here's a hint: https://github.com/rails/jquery-ujs/wiki/How-to-trigger-a-form-submit-from-code

**Comment by colinxfleming** [comment]
This has been a real mystical journey that's been high time and low reward, so I'm backlogging it again for now.

**Comment by colinxfleming** [comment]
Here's the story:
* `jquery-ujs` in webpack is required for this
* we'll know that works when $
* we should replace `form.submit()` with `$.rails.fire(form, 'submit')` or something similar in webpacker (see the ill-fated https://github.com/DCAFEngineering/dcaf_case_management/pull/1747 ) 
* this is made MUCH more complex by the fact that we're doublestacking jquery in both sprockets and webpacker

I would suggest revisiting this after we're no longer importing the following in sprockets (`app/assets`):
* jquery-ujs
* boostrap (in js and css)

This was tough, but now we know a lot about some very unexpected sprockets/webpack interactions.
*

**Comment by colinxfleming** [comment]
this is solved as part of our nuking webpack
