### ISSUE TITLE
Patient Details page should load at the top of the page, not scrolled down

### ISSUE THREAD

**Issue by lomky** [DARIAEngineering/dcaf_case_management#1824]
* **What are we trying to do?**

Right now when you scroll down the main page and click a patient, the Patient Details page loads also scrolled down. Can we make it load at the top of the page, instead?

* **What feature or behavior is this required for?**
Saving our Case Managers from Repetitive Stress Injuries!

* **How could we solve this issue? (Not knowing is okay!)**

I dunno!

**Comment by colinxfleming** [comment]
Steps to recreate:

* Log in to localhost:3000/ and pick 'DC' as your line, which will take you to the main case manager dashboard
* Scroll down to the 'Urgent Patients' section and click on a patient's name to go to their edit view
* This takes you to the bottom of their edit view, when it should be at the top!

**Comment by colinxfleming** [comment]
(Please leave for tech rebalanced volunteers!)

**Comment by Kevin-Wei** [comment]
Whoever wants to fight Turbolinks feel free... lol

**Comment by colinxfleming** [comment]
haha. so the short of it that @Kevin-Wei and I worked out is that this is probably a turbolinks issue -- turbolinks works by dynamically replacing the contents of the page body, and so it's preserving scroll location when it subs things in and out. So fixing this is probably a small dive into turbolinks and finding a way to snap to top in its library. (Let's not do anything wild like being like 'every time an anchor tab gets clicked, scroll to top' -- I'm sure there's some turbolinks setting we can do here.)

**Comment by jpkarvonen** [comment]
I didn't have too much time to look into this after a fresh install of the app on a new machine, but I did find this thread which focuses on the issue. This comment in particular may offer a solution: https://github.com/turbolinks/turbolinks/issues/181#issuecomment-423736911

**Comment by colinxfleming** [comment]
I'm electing to not think too hard about this, since it's pretty minor and nobody's complained in around three years; closing as a wontfix
