### ISSUE TITLE
Write generalizable analytics scripts for reporting over time

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#1830]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

One of the things we're trying to do with this project is to make things available to funds that they otherwise wouldn't have, and one of those things is decent analytics. I'm attaching here a CSV of fake data.

You are welcome to do this in whatever language you would prefer! Python or R is great, or any other language you're comfortable in. Please include detailed instructions for how to install dependencies and run the script, ideally that someone could copy and paste.

Please make any pull requests against the repo in https://github.com/DCAFEngineering/dcaf_analytics rather than here though! There's a directory in https://github.com/DCAFEngineering/dcaf_analytics/tree/master/analytics/base_reporting where you can put any work completed toward this goal.

* **What feature or behavior is this required for?**

Funds use this data to make informed judgments about their program. DCAF, for example, has used information like this to figure out what communities they could do a better job of serving, and getting a handle on whether they can expand their spending on abortion care.

* **How could we solve this issue? (Not knowing is okay!)**

Let's build a script that generates information about the following expenditures per month, per quarter, and per year. Use the `initial call date` column for purposes of figuring out what date something happened unless otherwise noted.

Here are some things that would be useful for funds to know. Please feel free to do as many of them as you are interested in -- don't feel like you have to do the whole set!

This is data that would be interesting to look at monthly and quarterly:

* number of patients (raw rows)
* number of cash promised to patients (where fund pledge values is present)
* number of pledged patients (where fund pledge is present and `Pledge sent` is true)

And this quarterly and yearly data:

* how many patients where pledge sent is true have gone to each clinic? (e.g. how much is a fund working with a clinic?)

You should also feel free to poke at anything that looks interesting to you! And feel free to use your discretion at how to report results. You have wide leverage here so go wild.

* **Anything else?**

Again, please make pull requests against https://github.com/DCAFEngineering/dcaf_analytics !

**Comment by colinxfleming** [comment]
Also these are all fake records, so if there's a weird pattern in the data, it's probably that the script I used to generate them isn't that great.

**Comment by colinxfleming** [comment]
[fake_daria_data.zip](https://github.com/DCAFEngineering/dcaf_case_management/files/3746268/fake_daria_data.zip)

**Comment by minhtranbear** [comment]
commenting on this to claim as work for today

**Comment by ealiao** [comment]
The start of some analysis in R:
`require(ggplot2)
require(dplyr)
require(readr)


### REPLACE patient_data_export_20191019.csv WITH THE NAME OF YOUR DOC ###
df <- read.csv("patient_data_export_20191019.csv")


# Data Cleaning -----------------------------------------------------------
df$Initial.Call.Date <- as.Date(as.character(paste(df$Initial.Call.Date)), format="%m/%d/%y")
df$Initial.Call.MonthYear <- format(as.Date(df$Initial.Call.Date), "%Y-%m")


# Total Patients by Month, Quarter ----------------------------------------
monthly_patients <- df %>% 
  group_by(Initial.Call.MonthYear, Line) %>%
  summarise(freq = n())

monthly_patients$Line <- as.character(paste(monthly_patients$Line))
monthly_patients$Initial.Call.MonthYear <- paste0(monthly_patients$Initial.Call.MonthYear, '-01')
monthly_patients$Initial.Call.MonthYear <- as.Date(monthly_patients$Initial.Call.MonthYear, "%Y-%m-%d")

ggplot(monthly_patients, aes(x=Initial.Call.MonthYear, y=freq, color=Line)) + 
  geom_line() + geom_point() + 
  labs(title ="Total Patients by Month", x = "Initial Call Month", y = "Patients") +
  theme_minimal() + theme(axis.text = element_text(size=12),
                          axis.text.x = element_text(angle = 90),
                          axis.title = element_text(size=16),
                          plot.title = element_text(size=24),
                          axis.title.y = element_text(margin = margin(r = 10)),
                          axis.title.x = element_text(margin = margin(t = 15)))`

**Comment by colinxfleming** [comment]
@ealiao did some incredible work in shiny that I am posting in here: https://codefordc.slack.com/archives/C0E6APB36/p1573004761218900

```
library(shiny)
library(highcharter)
library(dplyr)

# Define UI for data upload app ----
ui <- fluidPage(
  
  # App title ----
  titlePanel("DARIA Analytics"),
  
  # Sidebar layout with input and output definitions ----
  sidebarLayout(
    
    # Sidebar panel for inputs ----
    sidebarPanel(
      
      # Input: Select a file ----
      fileInput("file1", "Choose CSV File",
                multiple = FALSE,
                accept = c("text/csv",
                           "text/comma-separated-values,text/plain",
                           ".csv")),
      
      # Horizontal line ----
      tags$hr()
      
    ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      # Output: Data file ----
      h3("Patients by Month and Line"),
      highchartOutput("patients_by_month")
    )
  )
)

# Define server logic to read selected file ----
server <- function(input, output) {
    
    output$patients_by_month <- renderHighchart({
      req(input$file1)
      
      df <- read.csv(input$file1$datapath)
      
      # Clean Data
      df$Initial.Call.Date <- as.Date(as.character(paste(df$Initial.Call.Date)), format="%m/%d/%y")
      df$Initial.Call.MonthYear <- format(as.Date(df$Initial.Call.Date), "%Y-%m")
      df$Initial.Call.MonthYear <- as.Date(paste0(df$Initial.Call.MonthYear, '-01'), "%Y-%m-%d")
      df$pledged <- df$Pledge.sent == TRUE & df$Fund.pledge > 0 & !is.na(df$Fund.pledge)
      df$Line <- as.character(paste(df$Line))
      
      
      # Total Patients by Month
      monthly_patients <- df %>% 
        group_by(Initial.Call.MonthYear, Line) %>%
        summarise(freq = n())
      
      hc <- hchart(monthly_patients, "line", hcaes(x = Initial.Call.MonthYear, y = freq, group = Line)) %>%
        hc_add_theme(hc_theme_smpl())
      hc
    })
  
}

# Create Shiny app ----
shinyApp(ui, server)
```

We were trying to explore something like this with mode analytics but I wonder if another approach might be to stand up an analyzer app like this that people can load an export into and go wild on. Benefits to this approach:

* data sciencey people would have a bunch of hacknight tickets/reports to build
* empower basically anyone with a DARIA export to look at charts with minimal technical expertise
* the ruby team has basically never gotten to the reporting module

Scary things about this approach:

* don't know how secure and safe shiny is
* don't know anything about shiny really
* do we have the R expertise to manage this? (probably @ealiao does at least?)

**Comment by colinxfleming** [comment]
OBE
