### ISSUE TITLE
Practical Support Layout 

### ISSUE THREAD

**Issue by Elexc** [DARIAEngineering/dcaf_case_management#1839]
**Job:** When a case manager is adding practical support, they wants to be able to quickly add a new entry and manage the list of practical support, so that they can document the practical support for the patient. 

**What are we trying to do?** 
   - Improve the hierarchy and readability of the content
   - Revise the copy to be clear, concise, and consistent 
  

**Tasks**
- Changing the table + entry layout 
- Make the naming of the fields consistent in the list and new entry

**Rough sketch**
![IMG_8102](https://user-images.githubusercontent.com/17213530/67347278-95ea8500-f50f-11e9-8844-9e15082fcca6.JPG)

**Wireframe**
TBD

**Design details**
TBD

**Comment by Elexc** [comment]
I'm working on this!

**Comment by colinxfleming** [comment]
@colomasm is taking a look at this and @colinxfleming is going to make a connection between some funders who use psup and @colomasm

**Comment by colinxfleming** [comment]
abandoning for the time being
