### ISSUE TITLE
Refix patient ids to be more random

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#1900]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
our current ids follow the old pattern that DCAF had, which generates ids that aren't REALLY unique. @verbingthenoun reports seeing duplicates in the course of looking up people for data entry, which is not an ideal behavior (and a flaw with the method of generating IDs that we adopted from DCAF pre-DARIA). We should explore generating an actual unique identifier, or pressing a different identifier into service.

* **What feature or behavior is this required for?**
Actual unique ids for data entry people to search by when doing fulfillments.

* **How could we solve this issue? (Not knowing is okay!)**
I think the only places we use ID are the search and pledge generation forms. Clinics also use them in giving funds remits.

I think to decide what we need, we need answers to the following:
* do non-dcaf funds use generated ids for anything besides pledge generation? (probably not, right?)
* is it safe to surface these? (I think so but not sure)
* what can we give to clinics? Do they need something that looks like our current pattern but is totally scrambled, or can we do like a full on hash (e.g. `af5c32b`) or something?

* **Anything else?**
stems from a conversation with @verbingthenoun

**Comment by mdworken** [comment]
@colinxfleming regarding surfacing these, common guidelines for retroactive data analysis/"chart reviews" specify that a record is NOT considered anonymized if a matching code exists anywhere. Therefore, I propose that these should not ever be exportable, but viewable within the app for non-archived patients should be fine.

**Comment by colinxfleming** [comment]
that makes sense to me. That gives us two options that I can think of:
* take the UUID off the export, and use a subset of that (e.g. last 6 or 8 chars) as the identifier for clinics
* keep the UUID on the export, and continue using the `patient_identifier` or whatever field it's called, but generate it more randomly; continue to not export it

Which of those do you think would be the better option?

**Comment by colinxfleming** [comment]
closing since it's been two years
