### ISSUE TITLE
UX Ideation Meeting

### ISSUE THREAD

**Issue by sofijaj** [DARIAEngineering/dcaf_case_management#1930]
I'd like to organize an ideation meeting to bring DCAF CMs and Developers together sometime in mid or late March 

* **What are we trying to do?**
--give CMs and coders a chance to meet and chat about DARIA
--allow CMs and coders to express issues and do some creative problem solving 
--take a high level look at DARIA and figure out a way to 
--EAT

* **What feature or behavior is this required for?**

* **How could we solve this issue? (Not knowing is okay!)**

* **Anything else?**
I'm going to be building this up for the next few weeks so I'll add more content here.

**Comment by colinxfleming** [comment]
wontfix for the time being. (remember when we were still planning mass in person events? yikes)
