### ISSUE TITLE
Handoff within DARIA

### ISSUE THREAD

**Issue by sofijaj** [DARIAEngineering/dcaf_case_management#1931]
* **What are we trying to do?**
--At the end of each shift DCAF volunteers write a handoff email to the next volunteer(s) on shift. We're curious if this would be possible to do this handoff within DARIA to reduce the amount of replication and paperwork done by CMs and also keep this data outside of email as much as possible.

* **What feature or behavior is this required for?**
¯\_(ツ)_/¯

* **How could we solve this issue? (Not knowing is okay!)**
--Open text field
--Report pulled based on Activity Log

* **Anything else?**

**Comment by colinxfleming** [comment]
I think this is a good idea, and I think calling out the value of not emailing stuff back and forth is right on. Here's what I think I'd like to know that will help us figure out how to approach this:

* what gets a patient to the handoff email vs not? Can we make it programmatic?
* how standard is this behavior around DCAF? does every CM do it different or is every CM pretty much compiling the same list?
* do non-DCAF funds have a similar practice when they hand off line lead?
* can we get an example in this issue of an example (with PII redacted)?

**Comment by sofijaj** [comment]
- what gets a patient to the handoff email vs not? Can we make it programmatic?
PTs typically go into the handoff email if:
-- we are actively working on their case and want the next CM to be aware of them 
-- their appointment is upcoming and the next CM needs to watch out for their call or call them back to confirm
--CM needs to call that PT back 
-CM hasn't been able to get ahold of that PT

- [ ] - @sofijaj add this to CM survey if we end up doing that

 

- how standard is this behavior around DCAF? does every CM do it different or is every CM pretty much compiling the same list?
--Every CM writes a handoff email, it's a big part of our duties
--Formatting, though, depends on the CM so all of our emails look slightly different depending on how we like to organize. Ex. I've started writing emails segmenting urgent cases from less urgent cases
--I don't think it would be a heavy lift for our CMs to switch to a more standard format, we format similarly enough already, especially if it's communicated out and a quick guide is available

- [ ] @sofijaj add to guick guide list


- do non-DCAF funds have a similar practice when they hand off line lead?
not sure @lwaldsc any idea?

- can we get an example in this issue of an example (with PII redacted)?
![Recommended Handoff Email](https://user-images.githubusercontent.com/60895168/75613426-9c12f280-5afb-11ea-97fe-c537a6eef7fc.PNG)
@harumhelmy made this awesome sampler that I believe most/all CMs use

**Comment by colinxfleming** [comment]
@harumhelmy 's email there is helpful context, thank you!

By programmatic I mean basically 'can we do this by just applying a rule based on information within daria'. Harum's email gets pretty granular, though hopefully that kinda information is in the notes.

It sounds like the Urgent function is doing a lot of the lifting on this right now. (Which is good, because that's why we put it in.)

What do you think the next step is here? Polling other funds and DCAF CMs, figuring out rules, something else?

**Comment by sofijaj** [comment]
what I copied to you isn't an email but a google doc attached to our coverage emaiul that Harum's put together to use as a template for writing these handoff notes. I'm going to forward you the coverage email so you have a better idea of why it's such a pain in the ass.

I agree Urgent function is doing a great job of this, but my concern is that it's used inconsistently and it isn't clear to CMs that they have to check in on those people. 

@colinxfleming do you think there's a way to just pull a list based off the Urgent indicator that could just serve as the handoff? I've done it in relational databases before-- just query for an active indicator and bada bing bada boom, list. 

@lwaldsc mentioned maybe just adding an a "callback" indicator-- that could also be used to pull a report within DARIA. 

From my perspective, next steps are:
1. run this by DARIA admins for all the funds (do we have a central email list?/let's create one!) and see if it's an actual vs a perceived issue. I don't want this having to go through a lot of back and forth, it's an upgrade that improves security and saves CMs time. I'm hoping nobody would object to that.
2. collect some ideas from the devs on how this could be done/if it's feasible. 

Both of these steps can be accomplished during the ideation meeting.

**Comment by colinxfleming** [comment]
hasn't become actionable in a few years; closing for now in the spirit of ruthless prioritization
