### ISSUE TITLE
Create "FAQ" like document for common errors/resolutions when setting up the app

### ISSUE THREAD

**Issue by mdworken** [DARIAEngineering/dcaf_case_management#1977]
A few I can think of off the top of my head

- [ ] Mongoid won't boot: this is usually mongoid not shutting down properly and won't boot again (usually just have to `mongod --repair` )
- [ ] Wrong node version:  Daria uses 10 but the new default is 13. This can lead to webpack giving errors about SHAs and missing asset files. (Logged it at https://discuss.rubyonrails.org/t/webpacker-gets-mad-when-using-default-locally-when-node10-expected/75003 )

**Comment by colinxfleming** [comment]
Do you think these gotchas might be a good fit for https://github.com/DCAFEngineering/dcaf_case_management/blob/master/docs/SETUP.md ? From the context it looks like this came up on repo setups.

**Comment by colinxfleming** [comment]
wontfix
