### ISSUE TITLE
'Delete patient' not working in sandbox

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#1979]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

Steps to recreate:
* log in to sandbox using the test@example.com account
* search for a patient (without a sent pledge) and go to their patient record by clicking the link
* click the big red Delete this patient button and affirm that yes, you want to do that
 
At this point, it should redirect you back to the main call list dashboard and flash a notice that it's deleted the patient.

Instead, it seems to do nothing?

* **What feature or behavior is this required for?**

Admins being able to delete dupe patients

* **How could we solve this issue? (Not knowing is okay!)**

No idea! Dig in and go bug squashing.

* **Anything else?**

**Comment by rudietuesdays** [comment]
I'm able to recreate on sandbox and locally, looks like it's responding with a 404 on first hit but succeeding on page refresh. Digging in more!

**Comment by colinxfleming** [comment]
@lperson can you do me a solid and take care of this? been meaning to take care of it for awhile

**Comment by alepbloyd** [comment]
Starting to take a look at this bad boy fyi
