### ISSUE TITLE
Let's talk about Practical Support Process Improvements

### ISSUE THREAD

**Issue by lomky** [DARIAEngineering/dcaf_case_management#2037]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Keep the processing of Practical Support Patients inside the application, and not out on whiteboards, etc.

* **What feature or behavior is this required for?**
Better experience for both funds and patients. 

* **How could we solve this issue? (Not knowing is okay!)**
Could be a list on the homepage like the urgent list? Maybe something else?

* **Anything else?**
s/o to NOAF for raising this! We'll want to make sure this works across funds too.

**Comment by colinxfleming** [comment]
At some point over the last year we added `Unconfirmed Practical Support Cases` which I think solves for this; declaring victory
