### ISSUE TITLE
Go through Google App Verification

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#2120]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
We're coming up on a domain limit for Oauth - google allows you 10 before you have to give them an explanation of who you are and what kinda ship you're running. We're there, so it's time.

* **What feature or behavior is this required for?**
Being able to continue to add new funds and keep oauth working.

* **How could we solve this issue? (Not knowing is okay!)**
Go through Google App Verification https://console.cloud.google.com/apis/credentials/domainverification and run thru the deal.

* **Anything else?**
admins! This is the rare issue that is behind a gated resource, so probably for @colinxfleming  / @lomky  to handle

**Comment by colinxfleming** [comment]
I submitted us for app verification thru google on 3/19.

**Comment by xmunoz** [comment]
Any updates?

**Comment by colinxfleming** [comment]
This is on me to bump - looks like next steps are going thru the steps here https://stackoverflow.com/questions/54231660/i-cant-deploy-google-oauth-app-in-heroku

**Comment by colinxfleming** [comment]
place to register individual domains which I think covers us: https://search.google.com/search-console/welcome?hl=en

**Comment by colinxfleming** [comment]
domains are officially verified

**Comment by xmunoz** [comment]
Cool! I'm going to try to add Sandbox back to verified domains list here, which we had previously removed to make space for a newly onboarded fund: https://console.cloud.google.com/apis/credentials?authuser=1&project=dcaf-single-sign-on-production

We need to add it back because:
- Sandbox should, as much as possible, closely mirror production 
- I want to test the omniauth upgrade before rolling it out to other sites (#2141)

**Comment by xmunoz** [comment]
Good news! I was able to add back Sandbox to our Google Oauth config. I updated the config vars in Heroku, restarted the app, and add my user (xmunoz@opentechstrategies.com) from the admin login. I was then able to successfully login with Google. I think we can mark this done?

Bad news! The instructions here for creating a new user on the command line no longer work:
https://github.com/DCAFEngineering/dcaf_case_management/blob/8264dd3b411c769d4c2bbc25225207151de708c7/docs/administering/SETTING_UP_A_NEW_INSTANCE.md#smoke-test-to-confirm-everything-is-working-right

I can open a separate issue for that.

**Comment by colinxfleming** [comment]
per conversation with @xmunoz I think we're all clear here!

**Comment by colinxfleming** [comment]
We Thought Wrong

**Comment by xmunoz** [comment]
> Proof of ownership is no longer required for push subscription URL domains. To verify your domain for other purposes (such as proving domain ownership for Google Workspace or accessing sensitive Google Search data for a site) please visit the[ Google Search Console ](https://support.google.com/webmasters/answer/9008080).

I think we can close this.
