### ISSUE TITLE
Making fulfillment date field easier to use for data entry volunteers?

### ISSUE THREAD

**Issue by verbingthenoun** [DARIAEngineering/dcaf_case_management#2148]
* **What are we trying to do?**
Procedure date field in Fulfillment tab requires date to be entered as mm/dd/yyyy. Volunteers are used to typing dates as anything from mm/dd/yy to m/d/yy for single-digit months and days. This introduces errors into the data entry process that require additional auditor time to correct and are not always corrected before records archive. In an ideal world, DARIA would autoconvert dates to mm/dd/yyyy format even if entered in a different format.

* **What feature or behavior is this required for?**
Pledge fulfillment data entry

* **How could we solve this issue? (Not knowing is okay!)**
Not sure

**Comment by colinxfleming** [comment]
might want to turn a designer loose on this question

**Comment by lomky** [comment]
@verbingthenoun Is this still a problem post-Postgres? It looks like the form now automatically pops up a date selector, and coerces the data into a date!

**Comment by verbingthenoun** [comment]
@lomky is this change live? Still looks exactly the same for me on DARIA. If not, is there somewhere I can see the test version?

**Comment by colinxfleming** [comment]
OBE
