### ISSUE TITLE
Better language around urgent patients?

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#2172]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

NOAF pointed out that `Urgent` in urgent patients is kinda inaccurate - it gets used in practice as the 'flag/share with other case managers'. I think this is the case with more than just NOAF, so I'd like to check and see if this is true generally and change it if it is.

* **What feature or behavior is this required for?**

this was a point of onboarding confusion for NOAF.

* **How could we solve this issue? (Not knowing is okay!)**

* do a quick check with a few funds to confirm that 'urgent' means 'shared' for them too; workshop 'Share with other case managers' language
* bump the language/terminology

* **Anything else?**

**Comment by colinxfleming** [comment]
(emailed DCAF/BAF/CAF about this, let's see whathappens)

**Comment by colinxfleming** [comment]
I'm pretty satisfied by the feedback from funds -- let's rename to `Shared Patients` and update the language in the popup and elsewhere. not sure I care too much about the db column name but we can do that as a gold medal version.

**Comment by colinxfleming** [comment]
@elimbaum you want to grab this? Don't worry about changing the db field or anything, just do the frontend display stuff.

**Comment by elimbaum** [comment]
is it `shared` like you and me are sharing management of this patient? or like i'm pointing it out to you? wondering if `flagged patient` is clearer.

**Comment by colinxfleming** [comment]
I think a little bit of both, but the intent is 'shared across case
managers'. The point at which the box gets checked in the notes partial
might be good for communicating this

**Comment by elimbaum** [comment]
ok! i got a little carried away with my refactoring; I may take this opportunity to learn a bit about pg migrations. if that doesn't pan out i'll just do the front end migration.
