### ISSUE TITLE
URL validation isn't strict enough

### ISSUE THREAD

**Issue by elimbaum** [DARIAEngineering/dcaf_case_management#2183]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

Validate URLs in config page (after #2162, #2157) more accurately.

* **What feature or behavior is this required for?**

Config URLs should be validated in a way that is helpful and correct. The URL specification is too broad - it allows things like LAN names (i.e. `https://server`) as well as IP addresses (i.e. `https://1.1.1.1` or even `https://100` [an abbreviated IP]).

* **How could we solve this issue? (Not knowing is okay!)**

We could use the [public suffix list](https://publicsuffix.org/) to determine if something looks like a valid website. Or, we could send a `HEAD` request to the entered URL and see if we get something back. One concern there might be that the entered URL may not be accessible by the server (but may be from the user's machine). I'm not sure if this is a legitimate concern, though. Also, sending network probes as part of a validation scheme seems a bit funky.

* **Anything else?**

**Comment by colinxfleming** [comment]
I thought about milestoning this but I think I'm gonna close instead. My reasoning is basically that this is a pretty slim problem vector and the work + probably an additional dependency we'd add wouldn't be a perfect sanitization. @elimbaum if you disagree let me know, I think you probably think about grimier security stuff than I do!
