### ISSUE TITLE
Add practical supports to seeds

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#2193]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

We have a model, practical support, that CMs use pretty heavily, but when we seed the database with test data, none of the patients have practical support entries. We should adjust our test data to fix this!

* **What feature or behavior is this required for?**

Having test/experimental data that reflects patients accurately; improving the developer experience a bit.

* **How could we solve this issue? (Not knowing is okay!)**

The code changes will need to be made in `seeds.rb`. Practical Support is similar, relationship-wise, to Calls, so you can adopt some of that code.

Not every patient needs a PracticalSupport entry. I would suggest finding `if i.even?` in the seedfile (around L127?) and adding it there.

Try taking a look at the tests for an example of a filled out PracticalSupport entry.

* **Anything else?**
stems from a very good idea by @lomky in #2192

**Comment by elimbaum** [comment]
oops looks like cameron did this last year and we forgot to close issue! i will take a quick look to see if there's anything else worth adding, but otherwise will close.
