### ISSUE TITLE
Add weeks at procedure to fulfillment partial

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#2213]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

`Weeks along at procedure` is a field that I believe is contained in the export, but not surfaced anywhere else. It would help one of our funds out if we could surface that in app; let's add it to the static information in the fulfillment partial.

* **What feature or behavior is this required for?**

Requested by fund to make their workflow a bit easier.

* **How could we solve this issue? (Not knowing is okay!)**
Let's add it below the pledge amount field on the fulfillment partial. I don't know exactly what the method is called off the top of my head, but should be discoverable.

* **Anything else?**
This partial right here: 

![image](https://user-images.githubusercontent.com/3866868/120042233-a9a57980-bfd7-11eb-9cd7-a73dab55d6f0.png)

The intent here is to make it accessible through the accountants workflow.

**Comment by elimbaum** [comment]
Cool! Just to make sure I'm understanding all the parts -- we do this first, then #2208 and friends, correct?

**Comment by elimbaum** [comment]
Also, I'm not totally clear on the change here - we already have `weeks along at procedure` dropdown on the fulfillment partial. Are we looking for an additional view of that value?

**Comment by colinxfleming** [comment]
yeah, you're right, and I embarrassingly seem to have lost my notes on this. I think the useful piece of information is 'was estimated gestation WAY OFF from real gestation', so let's use the estimated gestation on the main patient view:

![image](https://user-images.githubusercontent.com/3866868/120043941-dc04a600-bfda-11eb-8e54-a8a8cb34abad.png)

and have that be the piece of info we surface?

Thank you for pointing this out and keeping me honest!

re: order, we should be able to do these in most any sequence - I'll write em up so they don't depend on each other.

**Comment by elimbaum** [comment]
@colinxfleming, coming back to this one after some time, and i'm not really clear on what needs to be added -- is it that we should add `estimated gestation` to the bulleted list in the partial?

**Comment by colinxfleming** [comment]
@elimbaum let me follow up with the fund / my notes on this and let's come back to it, and point you toward something a little better defined instead, haha. I'll tag you in on another one (and untag you from this one)

**Comment by colinxfleming** [comment]
nobody's complained about this in two years so let's say nevermind unless it resurfaces
