### ISSUE TITLE
Fix postgres n+1 joins

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#2225]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

For expedience, we're adding some n+1 joins to some controllers. We shouldn't let that sit for too long though!

* **What feature or behavior is this required for?**

fast app

* **How could we solve this issue? (Not knowing is okay!)**

`git grep "n+1 join here"` to find these trouble spots; then adjust the controller code to use appropriate `includes` or `joins` to eliminate the n+1 joins.

* **Anything else?**

**Comment by elimbaum** [comment]
@colinxfleming how did you go about finding those n+1 joins? instinct, or some tool? in my googling around I saw a reference to some tool that finds n+1 joins for you and explains the issue and if that's what you were using would love to take a look!

**Comment by colinxfleming** [comment]
@elimbaum The old fashioned way, by looking at logs! Though I'm sure there are tools that do it better (I think `bullet` is the one that I've heard of?), and you should definitely feel welcome to install them and use them.

For an example of what I saw that made me say this was a problem, loading the main call list dashboard, we see that it's making the same set of queries over and over again with slightly different parameters:

```
[DEBUG]   User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
[DEBUG]   PaperTrailVersion Load (0.6ms)  SELECT "versions".* FROM "versions" WHERE "versions"."item_id" = $1 AND "versions"."item_type" = $2 ORDER BY "versions"."id" ASC LIMIT $3  [["item_id", 33], ["item_type", "Call"], ["LIMIT", 1]]
[DEBUG]   CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
[DEBUG]   PaperTrailVersion Load (0.7ms)  SELECT "versions".* FROM "versions" WHERE "versions"."item_id" = $1 AND "versions"."item_type" = $2 ORDER BY "versions"."id" ASC LIMIT $3  [["item_id", 34], ["item_type", "Call"], ["LIMIT", 1]]
[DEBUG]   CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
[DEBUG]   PaperTrailVersion Load (0.3ms)  SELECT "versions".* FROM "versions" WHERE "versions"."item_id" = $1 AND "versions"."item_type" = $2 ORDER BY "versions"."id" ASC LIMIT $3  [["item_id", 35], ["item_type", "Call"], ["LIMIT", 1]]
[DEBUG]   CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
[DEBUG]   PaperTrailVersion Load (0.7ms)  SELECT "versions".* FROM "versions" WHERE "versions"."item_id" = $1 AND "versions"."item_type" = $2 ORDER BY "versions"."id" ASC LIMIT $3  [["item_id", 36], ["item_type", "Call"], ["LIMIT", 1]]
[DEBUG]   CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
[DEBUG]   PaperTrailVersion Load (1.3ms)  SELECT "versions".* FROM "versions" WHERE "versions"."item_id" = $1 AND "versions"."item_type" = $2 ORDER BY "versions"."id" ASC LIMIT $3  [["item_id", 37], ["item_type", "Call"], ["LIMIT", 1]]
[DEBUG]   CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
[DEBUG]   Call Load (2.0ms)  SELECT "calls".* FROM "calls" WHERE "calls"."can_call_id" = $1 AND "calls"."can_call_type" = $2  [["can_call_id", 4], ["can_call_type", "Patient"]]
[DEBUG]   PaperTrailVersion Load (0.4ms)  SELECT "versions".* FROM "versions" WHERE "versions"."item_id" = $1 AND "versions"."item_type" = $2 ORDER BY "versions"."id" ASC LIMIT $3  [["item_id", 27], ["item_type", "Call"], ["LIMIT", 1]]
[DEBUG]   CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
[DEBUG]   PaperTrailVersion Load (0.7ms)  SELECT "versions".* FROM "versions" WHERE "versions"."item_id" = $1 AND "versions"."item_type" = $2 ORDER BY "versions"."id" ASC LIMIT $3  [["item_id", 28], ["item_type", "Call"], ["LIMIT", 1]]
[DEBUG]   CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
[DEBUG]   PaperTrailVersion Load (5.1ms)  SELECT "versions".* FROM "versions" WHERE "versions"."item_id" = $1 AND "versions"."item_type" = $2 ORDER BY "versions"."id" ASC LIMIT $3  [["item_id", 29], ["item_type", "Call"], ["LIMIT", 1]]
[DEBUG]   CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
[DEBUG]   PaperTrailVersion Load (0.8ms)  SELECT "versions".* FROM "versions" WHERE "versions"."item_id" = $1 AND "versions"."item_type" = $2 ORDER BY "versions"."id" ASC LIMIT $3  [["item_id", 30], ["item_type", "Call"], ["LIMIT", 1]]
[DEBUG]   CACHE User Load (1.7ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
[DEBUG]   PaperTrailVersion Load (4.7ms)  SELECT "versions".* FROM "versions" WHERE "versions"."item_id" = $1 AND "versions"."item_type" = $2 ORDER BY "versions"."id" ASC LIMIT $3  [["item_id", 31], ["item_type", "Call"], ["LIMIT", 1]]
[DEBUG]   CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
```

So that's the same user query over and over, which isn't that big of a deal because we cache it. But it's also a hit of the versions table with a different `item_id`, over and over; those are all rapid fire db queries and it's pretty taxing and slow. The same thing is going on with calls table queries, if a patient has a call.

**Comment by elimbaum** [comment]
right, gotcha. was noticing some of those. so in that case specifically we would want a single query to load all of the users, right?

**Comment by colinxfleming** [comment]
Yeah - compare that to the queries that load the /accountants page, where we've taken steps to prevent n+1 joins -- you'll see that rather than loading patients and then loading individual objects in individual queries, we load all the patients in one query, all the related clinics in one query, and all the related fulfillments in one query.

```
[INFO ] GET     "/accountants"  for 127.0.0.1  at 2021-07-15 10:09:25 -0400
[DEBUG]   User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
[INFO ] === Processing by AccountantsController#index as HTML
[DEBUG]   Patient Load (2.7ms)  SELECT "patients".* FROM "patients" WHERE "patients"."pledge_sent" = $1 ORDER BY "patients"."pledge_sent_at" DESC  [["pledge_sent", true]]
[DEBUG]   Clinic Load (43.8ms)  SELECT "clinics".* FROM "clinics" WHERE "clinics"."id" IN ($1, $2, $3, $4)  [["id", 2], ["id", 3], ["id", 1], ["id", 4]]
[DEBUG]   Fulfillment Load (1.5ms)  SELECT "fulfillments".* FROM "fulfillments" WHERE "fulfillments"."can_fulfill_type" = $1 AND "fulfillments"."can_fulfill_id" IN ($2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)  [["can_fulfill_type", "Patient"], ["can_fulfill_id", 36], ["can_fulfill_id", 35], ["can_fulfill_id", 34], ["can_fulfill_id", 33], ["can_fulfill_id", 32], ["can_fulfill_id", 31], ["can_fulfill_id", 20], ["can_fulfill_id", 19], ["can_fulfill_id", 18], ["can_fulfill_id", 17], ["can_fulfill_id", 16], ["can_fulfill_id", 15], ["can_fulfill_id", 14], ["can_fulfill_id", 13], ["can_fulfill_id", 12], ["can_fulfill_id", 11], ["can_fulfill_id", 4]]
[INFO ]   Rendering accountants/index.html.erb within layouts/application
```

**Comment by elimbaum** [comment]
I installed the [Bullet](https://github.com/flyerhzm/bullet) gem, and it is very helpful. However... it is not reporting _any_ N+1 Queries; only eager loading. I'm not totally clear what this means, and it's suggested fixes haven't been working. Here's what that looks like:

```
2021-07-16 00:34:20[WARN] user: root
GET /
USE eager loading detected
  Patient => [:calls]
  Add to your query: .includes([:calls])
Call stack
  /usr/src/app/app/models/concerns/call_listable.rb:86:in `recently_called_by_user?'
  /usr/src/app/app/models/concerns/call_listable.rb:11:in `block in call_list_patients'
  /usr/src/app/app/models/concerns/call_listable.rb:11:in `reject'
  /usr/src/app/app/models/concerns/call_listable.rb:11:in `call_list_patients'
  /usr/src/app/app/views/dashboards/index.html.erb:14:in `_app_views_dashboards_index_html_erb__1526452174914046514_34080'
```

I think the reason it's not working has to do with how we've declared associations between models (i.e. with `belongs_to` and `has_one`), so I am reading up on that to see if we're missing anything.

**Comment by colinxfleming** [comment]
I took a look at this, and I can recreate what you're seeing. I've got a small journal entry in here about how I looked at this - hopefully it helps some? If it doesn't and you're still kinda stuck, I'd say ask in slack or drop this one  and we'll point you towards another!

I think when I read that bullet output, I read `USE eager loading detected` as the recommendation/diagnosis rather than the status - pretty confusing and unintuitive , but I _think_ based on what we know about these calls (which def do not use eager loading) what it's saying is:
* at `GET /`, there is a problem that could be solved with eager loading
* you can fix it by eager loading `calls` onto `Patient` using `includes` 
* the function calling it is `recently_called_by_user?`, called in `call_list_patients`

So armed with this knowledge (and the ref doc for includes at https://api.rubyonrails.org/v6.1.4/classes/ActiveRecord/QueryMethods.html#method-i-includes ) I cracked open `call_listable.rb`, and looked at `call_list_patients`. That, along with several other spots, uses a method called `ordered_patients` that loads patients from `CallList` objects.

Here's what that method looks like:

```
  def ordered_patients(line)
    # n+1 join here
    call_list_entries.includes(:patient)
                     .where(line: line)
                     .order(order_key: :asc)
                     .map(&:patient)
                     .reject(&:nil?)
  end
```

so this scans - we even do some `includes`-ing, but not with calls.

Looking at the activerecord docs, it says there's a trick we can use for nested relationships:

![image](https://user-images.githubusercontent.com/3866868/127804698-bd30b37a-26fd-48cf-adc3-8be519292397.png)

So I tried changing the includes line to eager load patient calls: `call_list_entries.includes(patient: [:calls])`

and the bullet part of console output changed to the fulfillments complaint, and a different `calls` spot where we need to eager load. So I guess that's progress 😂 

```
GET /
USE eager loading detected
  Patient => [:fulfillment]
  Add to your query: .includes([:fulfillment])
Call stack
  /Users/colin/repos/dcaf_case_management/app/models/concerns/statusable.rb:27:in `status'
  /Users/colin/repos/dcaf_case_management/app/views/dashboards/_table_content.html.erb:44:in `block in _app_views_dashboards__table_content_html_erb___2671020301886237242_40840'
  /Users/colin/repos/dcaf_case_management/app/views/dashboards/_table_content.html.erb:25:in `each'
  /Users/colin/repos/dcaf_case_management/app/views/dashboards/_table_content.html.erb:25:in `_app_views_dashboards__table_content_html_erb___2671020301886237242_40840'
  /Users/colin/repos/dcaf_case_management/app/views/dashboards/index.html.erb:11:in `_app_views_dashboards_index_html_erb__1390838249851772147_34140'


[WARN ] user: colin
GET /
USE eager loading detected
  Patient => [:calls]
  Add to your query: .includes([:calls])
Call stack
  /Users/colin/repos/dcaf_case_management/app/models/concerns/statusable.rb:47:in `days_since_last_call'
  /Users/colin/repos/dcaf_case_management/app/models/concerns/statusable.rb:31:in `status'
  /Users/colin/repos/dcaf_case_management/app/views/dashboards/_table_content.html.erb:44:in `block in _app_views_dashboards__table_content_html_erb___2671020301886237242_41540'
  /Users/colin/repos/dcaf_case_management/app/views/dashboards/_table_content.html.erb:25:in `_app_views_dashboards__table_content_html_erb___2671020301886237242_41540'
  /Users/colin/repos/dcaf_case_management/app/views/dashboards/index.html.erb:22:in `_app_views_dashboards_index_html_erb__1390838249851772147_34140'
```

**Comment by colinxfleming** [comment]
To address some off-list complaints about exports not working cleanly, I added bullet and fixed a couple of the n+1s in tests and call lists. That said, we've still got at least a few that bullet isn't catching, so I've left those comments in; when we've gotten rid of those we should close this issue, but keeping it open fornow.

**Comment by colinxfleming** [comment]
I think we can close this as we're in a substantially better place than we were over the summer.
