### ISSUE TITLE
Budget bar shouldn't show pledges for patients who have been resolved without fund

### ISSUE THREAD

**Issue by lomky** [DARIAEngineering/dcaf_case_management#2339]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Make it so the budget bar only shows live pledges

* **What feature or behavior is this required for?**
At a glance budget accuracy.

* **How could we solve this issue? (Not knowing is okay!)**

Not sure, but we are active _not_ going to:
 - remove/change the pledged value on the patient
 - remove the value from any other output its currently in
 
because some funds use this data, even if the patient doesn't ultimately need the pledge, and we don't want to disrupt that.

* **Anything else?**

**Comment by colinxfleming** [comment]
@DarthHater this is probably an effort in going into `Patient#pledged_status_summary` and adjusting the filters. glhf

**Comment by lomky** [comment]
So it looks like we're good here! 

https://github.com/DARIAEngineering/dcaf_case_management/blob/44ea24739aab8076ddc6f08ddf10330f4b86233b/app/models/patient.rb#L77-L79

And I tested out both an `unpledged, resolved without fund` and a `pledged, resolved without fund` patient, both disappear from the budget bar.
