### ISSUE TITLE
Set up Danger in CI

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#2371]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Add Danger! to our codebase and write a few existing norms as rules.

* **What feature or behavior is this required for?**
 - We have a couple things where we just need to "Remember" to do things. Let's add Danger to our codebase so we can minimize human error!
 - In particular, let's alert on PRs if we:
   - if we add a field to any model, add a note to check Archive Patient (should we add the field there?)
   - if we add a field to any model, add a note to check Logging (should we filter this field from the logs?)

* **How could we solve this issue? (Not knowing is okay!)**
https://github.com/danger/danger#what-is-danger
https://danger.systems/reference.html

* **Anything else?**

**Comment by lomky** [comment]
@colinxfleming Lemme know if you can think of other things we'd want to add a message to a PR for!

**Comment by colinxfleming** [comment]
@lomky still something we should think about?

**Comment by lomky** [comment]
I'm still tempted but I hit a snag implementing it. I'd say low priority but still nice to have
