### ISSUE TITLE
New "Urgent Reset Options" config has a max value of 28, can that be noted in the config description?

### ISSUE THREAD

**Issue by hkang06** [DARIAEngineering/dcaf_case_management#2400]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

It looks like there's actually a max value at 28 for the "Urgent Reset Options" config (https://github.com/DARIAEngineering/dcaf_case_management/issues/2338). I arrived at that conclusion after BAF attempted to set at 30, got an "invalid value" error, and then trial-and-erroring it from 10 upward. 

* **What feature or behavior is this required for?**
"Urgent Reset Options" config (https://github.com/DARIAEngineering/dcaf_case_management/issues/2338)

* **How could we solve this issue? (Not knowing is okay!)**

Immediate/small solution: It's not a huge priority, but updating the prompt (currently reads: "Number of idle days until a patient is removed from the urgent list. Defaults to 6 days") to include the max value would be helpful from a UX perspective. 

For more questions (not urgent), see below. 

* **Anything else?**

The 28 day max is not an issue for BAF (a huge help to lift the max from 6 to 28!), but our BAF CM lead did share wonderings about whether there are any concerns about funds not un-checking the Urgent flag when cases are resolved. 

Our BAF CM lead shared that we always un-check the "urgent" flag once cases have been resolved, as opposed to letting the "urgent" flag lapse on its own. I.e., it's less of a concern that people *aren't* closing out cases and more about worrying we've let something slip through the cracks. Is there any concern from DARIA developers' POV about cases that aren't being closed out in a real/practical sense from any of the funds?

**Comment by colinxfleming** [comment]
The immediate action makes sense to me - I'm tagging this as a hacknight fix, I think it's a pretty good setup-training issue. So for the developer tackling this - please update the text to include the min and max days. You can find the source in `app/models/config.rb` and find the view by logging in and going to Admin > Config Management on the navbar.

To your broader question, our urgents behavior was something that came up in user testing pretty early - I found an early ref to it in https://github.com/DARIAEngineering/dcaf_case_management/issues/614 and https://github.com/DARIAEngineering/dcaf_case_management/issues/119 and maybe buried in another early issue or two. I think the general behavior we observed was that cleanup doesn't tend to happen in similar situations (or happens very inconsistently), so a low-intensity bot would be pretty helpful. Put another way - if BAF makes it a point to uncheck then I think that makes you all pretty far ahead of the curve!

**Comment by colinxfleming** [comment]
@elimbaum would you mind taking care of this if you get a sec in the near future? The immediate fix (including the max value in the help text) suggested by hannah should work great. Thank you!
