### ISSUE TITLE
CodeCov is reporting incorrect coverage numbers

### ISSUE THREAD

**Issue by lomky** [DARIAEngineering/dcaf_case_management#2401]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Debug and fix our connection to codecov which broke sometime in the last month or so.

* **What feature or behavior is this required for?**
* accurately report our very-high-tyvm test coverage

* **How could we solve this issue? (Not knowing is okay!)**
* I'm pretty stumped - CodeCov is constantly comparing us to a base commit that isn't our current main, but I couldn't figure out how to fix it in ~30m.

* **Anything else?**
this might need an org admin to fully fix, but debugging help welcome from anyone!

**Comment by colinxfleming** [comment]
yeah, I think this went down when we moved to github actions! Low intensity, thankfully, but we should def fix sooner or later.

**Comment by colinxfleming** [comment]
#2468 didn't work
