### ISSUE TITLE
Graduate Pledge Generation into full Objecthood

### ISSUE THREAD

**Issue by lomky** [DARIAEngineering/dcaf_case_management#2411]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Pull Pledge Generation out of in-code configuration and into its own object.

* **What feature or behavior is this required for?**
Stable application behavior

* **How could we solve this issue? (Not knowing is okay!)**
Right now this lives directly in the pledge geernation flow and is linked to a name set of the Fund object. Instead it should probably be a subobject of funds - needs to be optional!

* **Anything else?**
Do we need a frontend for these fields? Maybe just on one we create for the Fund object?

**Comment by colinxfleming** [comment]
I'm doing this -- it makes some stuff about generic pledge generation significantly easier, I think
