### ISSUE TITLE
Add an i18n translation for Fund

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#2422]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

![image](https://user-images.githubusercontent.com/3866868/140654722-af95cb50-5f1e-4c03-a363-5c86da84917f.png)

We're missing a translation key here, so toward the bottom there's ugmo html. We should put a translation key in and get rid of the ugmo html.

* **What feature or behavior is this required for?**

It's uglyand obviously kinda buggy.

* **How could we solve this issue? (Not knowing is okay!)**

I believe we add it under `activerecord.attributes.patient.fund_id` in `en.yml` and `es.yml`. However we're handling `clinic` or `clinic_id` in that namespace should be adaptable. Google translate for the word `fund` is fine.

* **Anything else?**
nah

**Comment by OwenFish** [comment]
Looks like this can be closed. Can somebody confirm?

**Comment by colinxfleming** [comment]
yep, I believe this is resolved! Marking closed
