### ISSUE TITLE
Github Actions artifacts aren't saved

### ISSUE THREAD

**Issue by elimbaum** [DARIAEngineering/dcaf_case_management#2430]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Download artifacts from github actions. Currently it seems like we are not saving artifacts (i.e. html and screenshots from system tests) even though that was supposed to be the default.

* **What feature or behavior is this required for?**
Debugging failing tests, particularly system tests.

* **How could we solve this issue? (Not knowing is okay!)**
[This guide](https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts) may help?

* **Anything else?**

**Comment by colinxfleming** [comment]
paging @DarthHater or @xmunoz for an assist on this one
