### ISSUE TITLE
js-routes is a problem

### ISSUE THREAD

**Issue by xmunoz** [DARIAEngineering/dcaf_case_management#2466]
This dependency cannot be upgraded, and it's unclear what function it serves. Either try to refactor this library out of DARIA or get it upgraded to the latest version.

**Comment by xmunoz** [comment]
I'm giving up on this. I don't know nearly enough about webpacker or our asset pipeline generally. See https://github.com/DARIAEngineering/dcaf_case_management/pull/2392 for what I've tried so far.

**Comment by colinxfleming** [comment]
we fixed this (by removing js-routes)
