### ISSUE TITLE
Better error pages

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#2474]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

Could use something a little snappier than the rails default 

<img width="695" alt="image" src="https://user-images.githubusercontent.com/3866868/148006774-9d1e6280-d9ac-4399-8725-d02112c90eee.png">

* **What feature or behavior is this required for?**

* **How could we solve this issue? (Not knowing is okay!)**

* **Anything else?**

**Comment by emtot22** [comment]
Mocks! https://www.figma.com/file/Zry1ECvlVlSylFFKc6AxVv/DCAF-2?node-id=203%3A752
