### ISSUE TITLE
"External pledges sum" in csv export: field values are no longer all numerical

### ISSUE THREAD

**Issue by hkang06** [DARIAEngineering/dcaf_case_management#2514]
* **What are we trying to do?**
Can we fix the "External pledges sum" field in the .csv export so that all the values are numerical and are summing correctly? See attached screenshot from a BAF export. I think it's been going on for a few months - I hadn't had time to look more closely last November/December when I first ran into the issue. 
<img width="820" alt="Screen Shot 2022-02-15 at 5 46 47 PM" src="https://user-images.githubusercontent.com/35978875/154162878-1d9046bc-9060-4344-9bbb-78310c203f79.png">

* **What feature or behavior is this required for?**

It's helpful to have all of these values be numbers when we're reporting out. I have a little R script that I run and it's been breaking because the values in this column aren't all numerical. 

* **How could we solve this issue? (Not knowing is okay!)**

I feel like folks who are smarter than me might be able to pinpoint this as a small tweak, but I have no clear clues as to where this is broken :)

* **Anything else?**

**Comment by colinxfleming** [comment]
I wouldn't confuse knowing some esoteric programming stuff for smarts! but yeah, definitely see the problem. We'll give it an eyeball at the next hacknight.
