### ISSUE TITLE
Bump refs to DCAF in user guide and readme

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#2552]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

This project is now an independent project; we should bump accordingly

* **What feature or behavior is this required for?**

* **How could we solve this issue? (Not knowing is okay!)**

* **Anything else?**

**Comment by lomky** [comment]
https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository

**Comment by colinxfleming** [comment]
once #2623 goes in we're ready for a repo rename

**Comment by colinxfleming** [comment]
doing this at EOW
