### ISSUE TITLE
Fix autodeploy to staging

### ISSUE THREAD

**Issue by lomky** [DARIAEngineering/dcaf_case_management#2578]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
* Keep our staging env up to date with `main`

* **What feature or behavior is this required for?**
Modern CI/CD!

* **How could we solve this issue? (Not knowing is okay!)**
Might be related to Heroku's security wipe?

* **Anything else?**
[Recent Action run](https://github.com/DARIAEngineering/dcaf_case_management/runs/6355921283?check_suite_focus=true)

**Comment by xmunoz** [comment]
Fixed! https://github.com/DARIAEngineering/dcaf_case_management/runs/6357608942?check_suite_focus=true
