### ISSUE TITLE
Post-rails 7: Encrypt note content

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#2586]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Encrypt note content at rest

* **What feature or behavior is this required for?**
Safety

* **How could we solve this issue? (Not knowing is okay!)**
Rails 7 has a nice feature that does this out of the box which is solid and we should take advantage of this

* **Anything else?**
Depends on rails 7

**Comment by colinxfleming** [comment]
https://guides.rubyonrails.org/active_record_encryption.html

**Comment by colinxfleming** [comment]
@mercedesb might be a good next-up if you've got headroom

**Comment by mercedesb** [comment]
Totally! I can work on it this week/weekend

**Comment by mercedesb** [comment]
Is there a place where we've shared the dev environment variables? (e.g. the dev master key) We can't commit them to git, but do we have another method for sharing these sensitive values?

For this issue, I just need the dev master key and then I can provide instructions for you to generate the creds needed for prod so that you don't have to share the prod master key.

**Comment by colinxfleming** [comment]
@mercedesb this app predates the rails secret handling and we never rolled it out; we're doing basically all the app config using a `SECRET_KEY_BASE` env var (and rails handles the absence of it cleanly, though also possible we have a fake fallback value set). So I _think_ it should work straight up without having to do anything too fancy?

**Comment by mercedesb** [comment]
Okee dokee. If we want to avoid using Rails secrets in any environment, I'll need to write a custom encryption key provider, which I can totally do. The recommended approach for ActiveRecord encryption is to use secrets but there's definitely a way around it. I'll keep working on it this week and should have something ready in a few days.

**Comment by mercedesb** [comment]
Ok! Looks like #2852 is good to go 🙂 it should be safe to deploy and handle the existing, non-encrypted notes. I included a rake task that you can run post-deploy to go through and encrypt all the current notes. If you do that, we'll then be able to remove the config that allows unencrypted note content in the next release.
