### ISSUE TITLE
Figure out how to delete an instance

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#2634]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

There's a high chance that we'll be dropping several clients before the end of the calendar year, and I don't want sensitive data to hang around for any longer than it needs to. I would like to write a playbook for dropping a fund from a software perspective, so that when someone asks we'll be ready.

I think this will probably happen around September at the earliest so having something by then is good.

* **What feature or behavior is this required for?**

fund management and administration

* **How could we solve this issue? (Not knowing is okay!)**

this should cover the 'delete rows associated with a fund, including relations and audit trails' parts. Probably not sessions. Probably should be run very very very manually and have some kind of safety switch.

* **Anything else?**

@lomky can you handle this one?

**Comment by lomky** [comment]
# Removing a Fund

## High Level Overview
To remove a fund from our production database we have to:
1) remove tenanted models (reversible)
2) remove the PaperTrails records (**irreversible**)
3) Delete the fund's row

We also have to do a few administrative things:
 - Remove the subdomain configuration
 - Remove the fund from our List of Funds and Mailing List
 - Get final signoff of contract end & cease billing
 
Lastly, depending on the size of the fund, we should consider if we should adjust our infra sizing.

**Comment by lomky** [comment]
## Removing Production Data

```ruby
Rails.application.eager_load!
all_models = ActiveRecord::Base.descendants
models_fund_agnostic = [
  Fund
  ActiveRecord::SessionStore::Session,
  PaperTrail::Version,
  PaperTrailVersion]     
models_fund_dependent = [
  PledgeConfig,    
  PracticalSupport,
  Patient,
  Note,
  Line,
  Fulfillment,   
  ExternalPledge,
  Event, 
  Config,
  Clinic,
  CallListEntry,
  Call,
  ArchivedPatient,
  User]

# Prove to yourself all models are accounted for
all_models - models_fund_dependent - models_fund_agnostic
=> [ApplicationRecord(abstract)]

# Catch all the model counts for each fund to eyeball after
starting_counts = {}
Fund.all.sort.each do |fund|
  fund_counts = {}
  models_fund_dependent.each do |model|
    fund_counts[model.to_s] = model.where(fund_id: fund.id).size
  end
  starting_counts[fund.name] = fund_counts
end
fund_counts = {}
models_fund_agnostic.each do |model|
  fund_counts[model.to_s] = model.all.size
end
starting_counts['fund_agnostic'] = fund_counts

#save starting counts to file
$stdout = File.new('initail_state.out', 'w')
$stdout.sync = true
starting_counts
$stdout = STDOUT

#Lock our tenant!
Fund.all.pluck(:name,:id)
defunct_fund_id = #the fund you are removing
ActsAsTenant.current_tenant = Fund.find(defunct_fund_id)

##### DO NOT RUN THESE UNTIL current_tenant HAS BEEN SET
##### They can be undone, because we have PaperTrail, but lets not test that if we can help it
Patient.destroy_all
ArchivedPatient.destroy_all
[Note, Fulfillment, ExternalPledge, PracticalSupport, Call].each { |model| model.destroy_all }
[Clinic, Line, Config].each { |model| model.destroy_all }
User.destroy_all

# exit and restart to console to drop the ActsAsTenant.current_tenant
exit
```
```ruby
# Check the new overall state
models_fund_dependent = [ PledgeConfig, PracticalSupport, Patient, Note, Line, Fulfillment, ExternalPledge, Event, Config, Clinic, CallListEntry, Call, ArchivedPatient, User]
models_fund_agnostic = [ Fund, ActiveRecord::SessionStore::Session, PaperTrail::Version, PaperTrailVersion] 

post_deletion_counts = {}             
Fund.all.sort.each do |fund|          
  fund_counts = {}                    
  models_fund_dependent.each do |model|
    fund_counts[model.to_s.to_sym] = model.where(fund_id: fund.id).size
  end                                                                  
  post_deletion_counts[fund.name] = fund_counts                        
end                                                                    
fund_counts = {}                                                       
models_fund_agnostic.each do |model|                                   
  fund_counts[model.to_s.to_sym] = model.all.size                      
end                                                                    
post_deletion_counts['fund_agnostic'] = fund_counts                    
                                                                       
#save starting counts to file                                          
$stdout = File.new('post_deletion.out', 'w')                           
$stdout.sync = true                                                    
post_deletion_counts                                                   
$stdout = STDOUT

# diff those files!
# the other fund objects should not have changed significantly
# There should be a jump in PaperTrails corresponding to the total object count we've deleted
# IF AND ONLY IF everything looks good, let's continue.

# delete the PaperTrails
#  🚨 ⚠️ 🚨 ⚠️ 🚨 This is the point of no return. Once these are deleted, we cannot restore the funds information from the database

defunct_fund_versions = PaperTrail::Version.where_object(fund_id: id)
defunct_fund_versions.destroy_all
defunct_fund_changes = PaperTrailVersion.where_object_changes(fund_id: id)
defunct_fund_changes.destroy_all

# Finally, destroy the fund row
# Remove the fund
defunct_fund_id = #the fund you're removing!
fund = Fund.find(defunct_fund_id)
fund.destroy

exit
```

**Comment by lomky** [comment]
## Removing the Subdomain Configuration
We are effectively undoing the first three steps in [Setting up a new fund](https://github.com/DARIAEngineering/dcaf_case_management/blob/main/docs/administering/ONBOARDING_A_NEW_FUND.md#gathering-api-tokens-and-secrets)

- Configure Google OAuth (for Login with Google):
  -  Go to our [GCP project](https://console.cloud.google.com/apis/credentials?project=daria-services-multitenant)
  -  Open up DARIA Services Production from the list of Client IDs to edit
  -  Remove the Authorized redirect URI for the fund's subdomain
- Remove the DNS in Namecheap
  -  Open up the Namecheap control panel and head to Advanced DNS.
  -  Remove the CNAME Record for the host 
- Remove the subdomain in heroku
  -  Open up the pipeline in Heroku and go to the production instance, then open up Settings, then go to Domains.
  -  Click the edit icon for the fund's domain and select Remove Domain

**Comment by lomky** [comment]
@colinxfleming @xmunoz any initial thoughts before I clean this up into a docs entry?

**Comment by xmunoz** [comment]
All that sounds right to me. I believe when we remove the subdomain from Heroku it also cleans up the certs. Something to maybe keep an eye on.

**Comment by xmunoz** [comment]
Sentry has a 90 day retention I believe, and there is a chance fund information could also be in there. I think it's reasonable to just say that once we remove your site, all data is scrubbed after 90 days.

https://forum.sentry.io/t/on-premise-data-retention/8961
