### ISSUE TITLE
Update pledge form text for DCAF instance

### ISSUE THREAD

**Issue by harumhelmy** [DARIAEngineering/dcaf_case_management#2643]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?** 
To remove the gendered language in the pledge form generated by DARIA, i.e. "people in low-income situations" instead of "women." 
To have all pledge signatures be "DCAF Board President" as a default 

* **What feature or behavior is this required for?**
* Pledge generation!

* **How could we solve this issue? (Not knowing is okay!)**
Update the thing please!

* **Anything else?**
Thank you so much for all you do.

**Comment by colinxfleming** [comment]
OBE
