### ISSUE TITLE
Should we optionally display the weekly/monthly budget on the budget bar?

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#2658]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

More than one fund has reached out to me recently to ask for this. We've generally discouraged doing Real Budgeting in DARIA (excel is way better and more consistent than we'll ever be) but people are making pretty good arguments that some signals would be helpful.

@lwaldsc as one of the original intellectual architect of the budget bar interested in your thoughts - my recollection is that we didn't do this originally because we thought it would bum out DCAF CMs (one late case and there you go). but wonder if this is similarly a bummer for smaller funds.

* **What feature or behavior is this required for?**

not doing math

* **How could we solve this issue? (Not knowing is okay!)**

if we _were_ to do this, it would look like:
* config to toggle display on/off
* add some math to the budget bar like `(soft pledged: X) + (sent pledged: Y) = X+Y / (weekly budget) (Z%)`

* **Anything else?**

nah

**Comment by colinxfleming** [comment]
okay, let's do this. Specifically:

* Config to toggle this on/off called something `display_budget_bar_aggregate_data`, defaulting to having it off
* If it's on, add these calculations to the view. (I don't care how you get there, but not making additional database calls would be a nice bonus if possible!)

![image](https://user-images.githubusercontent.com/3866868/188252997-30233f48-febe-486f-b6d5-784c88073b53.png)

@elimbaum you're up!

**Comment by elimbaum** [comment]
you got it!! are those the four metrics we want?

**Comment by colinxfleming** [comment]
hm, great question. Let's start with the dollar figures and cut the percents, and see how close that gets us.

**Comment by elimbaum** [comment]
believe it or not! i am done with grad apps! and working on this!

**Comment by elimbaum** [comment]
frontend draft, open to comments!

<img width="1129" alt="Screen Shot 2022-11-22 at 22 34 22" src="https://user-images.githubusercontent.com/7085805/203464454-c83ae110-a6a4-4b8e-887c-1fa03d797920.png">

refactoring this a bit to make it easier to add more statistics in the future w/ out a bunch of copy paste.

**Comment by colinxfleming** [comment]
I agree that the pledging concept is kinda confusing - refers to both setting aside money in the CM's case, and actually sending the promise of money in the clinic's case - but those are the terminology conventions at the moment, so let's leave that as is for the time being.
