### ISSUE TITLE
Add way to track which fund is taking the lead on a solidarity case

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#2661]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

I was right, funds do want to know whomst running point on solidarity cases. Let's mark that down and increase the utility of this new field. 

* **What feature or behavior is this required for?**

better comms and gardens

* **How could we solve this issue? (Not knowing is okay!)**

probably a dropdown on abortion information with a list of funds in the external pledges rack. The current fund should be in there too. Might require a little tuning.

* **Anything else?**

Let's also affirm that there isn't a security concern here (or at least not one that's greater than the general external pledges tracker)

**Comment by elimbaum** [comment]
> better comms and gardens

get out

**Comment by colinxfleming** [comment]
@elimbaum  all yours

**Comment by elimbaum** [comment]
Should this go under `Abortion Information`, `Clinic Details`, or `Cost Details`?

**Comment by colinxfleming** [comment]
probably paired up with the solidarity pledge checkbox; if you gotta move it around to make it not ugly that's fine

**Comment by elimbaum** [comment]
ooh wait how bout this

- make solidarity a disabled checkbox (or just informational label)
- have a single dropdown for "handling fund"
- if `handling fund == current fund`, this is not a solidarity case
- if `handling fund != current fund`, this is a solidarity case

this way, maybe less redundancy in db.

however, happy to keep it simple with a separate checkbox and dropdown.

**Comment by elimbaum** [comment]
PR #2668 keeps separate DB values (solidarity, handling fund) but establishes some dependency between them. I may not be understanding the full picture so let me know if I'm off base with my assumptions.
