### ISSUE TITLE
help tooltips being displayed twice on navigation

### ISSUE THREAD

**Issue by elimbaum** [DARIAEngineering/dcaf_case_management#2667]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
on navigation away from the patient information page, the help tooltips (`(?)`) are momentarily doubled up. weird! see screenshot below.

* **What feature or behavior is this required for?**
good user interface

* **How could we solve this issue? (Not knowing is okay!)**
may need to run a debugger in browser to figure out what's causing this! could be something with turbolinks, but I don't know why the help tooltips are the _only_ UI element being doubled.

* **Anything else?**

screenshot:

<img width="1512" alt="Screen Shot 2022-07-26 at 22 03 22" src="https://user-images.githubusercontent.com/7085805/184434377-8d1082ef-5d2b-4e07-b000-2af752d4dc92.png">

**Comment by colinxfleming** [comment]
@elimbaum I can't seem to recreate this just from clicking around in sandbox. Can you include a step by step to recreate this?

**Comment by elimbaum** [comment]
ya! lemme see

**Comment by elimbaum** [comment]
I can reproduce on both Firefox and Safari on my Mac. Learning about the Firefox JS debugger to see if I can track down who's to blame!

**Comment by elimbaum** [comment]
way out of my depth but have discovered:

1. tooltips are being doubled because `activateTooltips` is being called twice because event `turbolinks:load` fires _twice per page load_
2. There's an issue discussing [here](https://github.com/turbolinks/turbolinks/issues/281).

Added a console log to the `activateTooltips` function. Timestamps are in ms — this is on page load. You can see the event fires twice.

<img width="317" alt="Screen Shot 2023-02-07 at 22 18 36" src="https://user-images.githubusercontent.com/7085805/217420666-d104e971-13fe-46de-9ab3-d6e3fcc1b2c7.png">

ok, so what do we do? Well, one interesting tidbit that is that the the "normal" tooltips (those with class `daria-tooltip`, as opposed to the cursed ones we're dealing with here) do NOT double. Probably something to do with the fact that we are _only_ calling the jquery `tooltip` function which must be idempotent. HOWEVER! the reason we are seeing doubling is because we blindly append a new span to the tooltip labels.

- Option 1: restructure checkbox and form input tooltips to look more like the normal tooltips, preventing cursed behaviors
- Option 2: figure out why `turbolinks:load` being fired twice (code-cleanliness-optimal)
- Option 3: add additional state (maybe an extra class) to signify that a tooltip has already been added
- Option 4: fuhgeddaboudit

**Comment by colinxfleming** [comment]
woof. incredible digging. 

turbolinks is weird and I think it's been superseded by `turbo`, which I _think_ does kinda the same thing, or very similar? So one option is declaring turbolinks bankruptcy and moving to turbo instead. (Another is declaring turbolinks bankruptcy and ditching it entirely, on the basis that this is not a performance-sensitive app and turbolinks historically causes more problems than it solves.)

Separately: I think when we rolled this out I tried pretty hard to do this with the data attribute. Maybe it is worth taking another shot at that now that we understand the problem better thanks to this v good writeup.

**Comment by elimbaum** [comment]
Ok, I can definitely give replacement/removal a look!

Separately: are you suggesting using a data attribute to mark whether we already have a tooltip, and thus not refiring?

**Comment by elimbaum** [comment]
@colinxfleming opening 2 PRs — one which removes turbolinks entirely and keeps it _old school_, and another which upgrades us to use `Turbo`. I'll fool around with Turbo for a bit and see how I like it, but both should get us (functionally) similar behavior, even if using Regular HTML Links™ is a bit passé. 😎
