### ISSUE TITLE
CSV export is timing out for DCAF in production

### ISSUE THREAD

**Issue by mdworken** [DARIAEngineering/dcaf_case_management#2676]
**Reproduction steps:** 
Log into daria on the live DCAF instance and hit "Export Anonymized CSV"

**Expected Behavior**
The csv successfully downloads.

**Actual Behavior**
The csv loads very slowly (about 70kbs) and times out before it finishes downloading.

Possible solutions:
1. Adjust heroku settings for either faster data transfer or longer timeouts?
2. Upload the CSV to an S3 bucket? It's about 10-12 mb now, which is pretty large. (This carries a LOT more security risk)
3. Refactor csv generation so that it's generated separately from being downloaded, and the most recently generated CSV is stored in memory on the rails server?

**Comment by colinxfleming** [comment]
this is resolved
