### ISSUE TITLE
Add i18n key for pledge_generated_by_id

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#2706]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

The `pledge_generated_by` field shows up in the changelog like so:
```
<span class="translation_missing" title="translation missing: en.activerecord.attributes.patient.pledge_generated_by_id">Pledge Generated By</span>: (empty)
```
ew.

* **What feature or behavior is this required for?**

Clean changelog
* **How could we solve this issue? (Not knowing is okay!)**
I think we handled this for Clinic? Do the same thing for the key. This will entail opening up `en.yml` and `es.yml` and adding keys. (Look for `clinic_id`.)

* **Anything else?**
nah

**Comment by mbichoffe** [comment]
working on this one!
