### ISSUE TITLE
Add a config to turn off base options in dropdowns

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#2717]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

Some funds would prefer not to have standard issue stuff in dropdowns - let's add a config to remove.

* **What feature or behavior is this required for?**

Fund usage, esp in non-pledge contexts

* **How could we solve this issue? (Not knowing is okay!)**
Config that, when 'yes', doesn't include any of the standard issue options that are hooked up to configs. For ex, insurance options should be just [] + the config, rather than [] + the standard set + the config. 

* **Anything else?**
fund request

**Comment by elimbaum** [comment]
"Standard options" appears in:

- **external_pledges_helper**
  - `external_pledge_source_options`
- **patients_helper**
  - `language_options`
  - `voicemail_options`
  - `referred_by_options`
  - `insurance_options`
- **practical_supports_helper**
  - `practical_support_options`
  - `practical_support_source_options` - may reuse external pledge source above.

think that's it. will start working through these.

**Comment by colinxfleming** [comment]
I think language you can leave as is, but yes please to the other stuff!
