### ISSUE TITLE
remove all contributors

### ISSUE THREAD

**Issue by xmunoz** [DARIAEngineering/dcaf_case_management#2720]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Remove all contributors dependency, which displays contributors in the readme.

* **What feature or behavior is this required for?**
Now this dependency is requesting new permissions, and given the nature of this project, we maybe don't want to advertise the contributors.

* **How could we solve this issue? (Not knowing is okay!)**
Clean up the readme, remove the dependency

* **Anything else?**

**Comment by colinxfleming** [comment]
this one was @lomky 's so tagging in her as reviewer

**Comment by lomky** [comment]
I concur 😭
