### ISSUE TITLE
'Duplicate patient' line error message displaying improperly

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#2761]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
![image](https://user-images.githubusercontent.com/3866868/204156992-35ce419a-765c-4dea-bd75-ac22405d1a5a.png)

That should be `line.name` not the line object!

* **What feature or behavior is this required for?**
Actionable error messages on duplicate patients. To recreate, make a new patient on the Guremike line, and then try to make that same patient on the Maru line.

* **How could we solve this issue? (Not knowing is okay!)**

* **Anything else?**

**Comment by channiemills** [comment]
hi! i can take this on
