### ISSUE TITLE
Optionally restrict county field to a dropdown

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#2771]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Some funds work only in service areas, and so geo matters a lot to them. We enumerate states since there aren't that many valid ones, but sometimes there are only so many counties funds care about, so it might make sense to enumerate these as well with a dropdown rather than just the free text input field.

* **What feature or behavior is this required for?**
cleaner patient info tracking

* **How could we solve this issue? (Not knowing is okay!)**
This is probably a config of comma separated values where each value is a county, and if the config is set this means that you get a dropdown something like `[nil, values, ..., other]` instead of the free text field. (My hunch is that we don't need to support free text Other values, and in fact that would be a bit of a hassle.)

* **Anything else?**
nah

**Comment by elimbaum** [comment]
some more specifics:

- always display current value in dropdown, as we do in other places (don't clobber old values)
- also provide an `other` field in case the county isn't listed

@colinxfleming — should a new text box pop up if you select other, or should it just be `other (see notes)` as we do for practical supports?
