### ISSUE TITLE
Recent production issue -- investigation required

### ISSUE THREAD

**Issue by xmunoz** [DARIAEngineering/dcaf_case_management#3099]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
We recently deployed 68905719 to production, and it caused the data in the clinics list to get munged.
![DariaIssue](https://github.com/DARIAEngineering/dcaf_case_management/assets/1065196/f8693b33-3aa1-402d-aaf3-c3e0a4c4c30b)

Issue was resolved by rolling back to d84016bb. [Here is the diff](https://github.com/dARIAEngineering/dcaf_case_management/compare/d84016bb...68905719). One or more of these upgrades is likely causing the issue. Figure out which one and fix it. Also, probably a good idea to write a test for this moving forward.

* **What feature or behavior is this required for?**
Releasing!

* **How could we solve this issue? (Not knowing is okay!)**
We suspect there is something going on with a newer version of Active Record, but this is unconfirmed.

* **Anything else?**
Nope!

**Comment by colinxfleming** [comment]
We're out of the woods on this. Some kinda fight with activerecord and deterministic encryption specifically which is annoying but maybe to be expected. I resolved this by taking a snapshot of clinic names and then running manual updates (grateful that this table is small).

I think everywhere else we use non-deterministic encryption so this was only a problem on the clinic name in particular.

I think we can consider this resolved - I've spot checked a fund and we're on the latest commit + clinic names aren't scrambled.
