### ISSUE TITLE
Deprecation Warning: `Rails.application.secrets` is deprecated in favor of `Rails.application.credentials`

### ISSUE THREAD

**Issue by lomky** [DARIAEngineering/dcaf_case_management#3108]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Rails has deprecated one thing for another. Let's clean up to match

* **What feature or behavior is this required for?**
```
DEPRECATION WARNING: `Rails.application.secrets` is deprecated in favor of `Rails.application.credentials` and will be removed in Rails 7.2. (called from <top (required)> at /home/runner/work/dcaf_case_management/dcaf_case_management/config/environment.rb:5)
```

* **How could we solve this issue? (Not knowing is okay!)**
Hopefully straightforward, should be good info out in the world.

* **Anything else?**

**Comment by xmunoz** [comment]
It looks like there are multiple deprecation warnings originating from Rails now. Opened #3128 to keep track of them all, and will close this as a dupe (even though you opened this one first!)
