### ISSUE TITLE
Rails deprecation warnings

### ISSUE THREAD

**Issue by xmunoz** [DARIAEngineering/dcaf_case_management#3128]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Eliminate Rails deprecation warnings, so we aren't caught off guard with Rails configuration options are completely removed.

* **What feature or behavior is this required for?**
Keeping things up to date.

* **How could we solve this issue? (Not knowing is okay!)**
Here are the deprecation warnings when the test suite runs:
```
DEPRECATION WARNING: `Rails.application.secrets` is deprecated in favor of `Rails.application.credentials` and will be removed in Rails 7.2. (called from <main> at /home/runner/work/dcaf_case_management/dcaf_case_management/config/environment.rb:5)
DEPRECATION WARNING: Setting action_dispatch.show_exceptions to false is deprecated. Set to :none instead. (called from block (4 levels) in <class:LinesControllerTest> at /home/runner/work/dcaf_case_management/dcaf_case_management/test/controllers/lines_controller_test.rb:34)
```

* **Anything else?**
Nope, should be pretty straight forward.

**Comment by mbichoffe** [comment]
Working on it!
