### ISSUE TITLE
translation missing: en.activerecord.attributes.patient.support_date

### ISSUE THREAD

**Issue by xmunoz** [DARIAEngineering/dcaf_case_management#3134]
Add missing translation to prevent html dump to patient history table. I'm working on the Spanish line in [sandbox](https://sandbox.dariaservices.com/patients/6224/edit).
<img width="876" alt="Screenshot 2024-01-11 at 16 09 25" src="https://github.com/DARIAEngineering/dcaf_case_management/assets/1065196/afeafa32-36ad-4c5c-9df3-d9a672462d78">

**Comment by mbichoffe** [comment]
Created a PR: https://github.com/DARIAEngineering/dcaf_case_management/pull/3141
