### ISSUE TITLE
Add "Procedure Type" to Patient

### ISSUE THREAD

**Issue by lomky** [DARIAEngineering/dcaf_case_management#3174]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
* Backend:
  * Add a new field called "Procedure Type" to the Patient Model
  * Field should be Exportable and retained on the Archived Patient Model
  * Field should be Customizable
    * Default options - "Medical, Telehealth Medical, Procedure"
  * Add proper seeds 
- Frontend:
  - Expose this field as a dropdown under the Abortion Information tab, Clinic information section

**What feature or behavior is this required for?**
Fund request!

**How could we solve this issue? (Not knowing is okay!)**
Backend implementation should look very similar to the [`insurance` field](https://github.com/search?q=repo%3ADARIAEngineering/dcaf_case_management%20%3Ainsurance&type=code).

* **Anything else?**

**Comment by colinxfleming** [comment]
This sounds good to me. Two things to consider:
* should funds be able to turn this off? my instinct is no but interested in your thoughts
* what's the distinction between Medical and Procedure?

**Comment by lomky** [comment]
Could we make it only show if the fund has configured values? And then the meaning of each value is unimportant to us - its whatever folks want to use it for

**Comment by colinxfleming** [comment]
I think 'only show if there are configured values' sounds great! Let's promote this to active
