### ISSUE TITLE
Minor js bug - Status on patient dashboard now editable

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#3233]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

This should be a display field, and looks like one, but appears editable now - 

<img width="1178" alt="image" src="https://github.com/user-attachments/assets/2455b9be-555c-430b-8a65-6e4e33ab0040">

To recreate, open a patient record and edit the status in the patient dashboard. (Note that it doesn't actually save db state!)

* **What feature or behavior is this required for?**

keeping uneditable data from appearing editable 

* **How could we solve this issue? (Not knowing is okay!)**

change the input element 

* **Anything else?**

**Comment by rkaufman13** [comment]
I'll grab this
