### ISSUE TITLE
Better patient mocking based around more realistic patient stories

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#814]
@lomky raised the excellent point that at this point, we know what patterns are in our patient stories, yet our seeds and test fixtures don't really reflect these stories. Adjusting them to reflect reality is likely to be time very well spent, both for realistic testing and so that developers can understand what things look like in livefire situations.

I've never done story based testing factories, so I defer to others on the team. What can we provide, besides patterns we tend to see in DCAF patients?

**Comment by lomky** [comment]
I am interested in case manager input on these topics in particular:
  - What are realistic mixtures of different patient info
    - voice mail preference, other contact info, special circumstances
  - What are realistic examples of sparse patients, where we have only the bare minimum of information
    - name and phone number?
  - how many times are reasonable to have contacted a person?
     - how many times are not reasonable, but also not impossible?
     - over what timespan

These also do not have to be perfectly representative, we're just looking for more realistic.

**Comment by colinxfleming** [comment]
@lwaldsc can I tag you in to work out the business side of this with @lomky ? 

I defer to @lomky but I think it might make sense to aim for the following three test cases to start, and we can expand from there:
* patient who called and left a voicemail but who we haven't called back yet (minimal information case)
* patient who's had a few live calls but hasn't had a pledge sent yet
* patient with a sent pledge

Thoughts about that plan of attack @lomky ?

**Comment by lomky** [comment]
That looks like a solid base set, @colinxfleming! :100: I generally like testing with a set of standard cases and a set of edge cases. So we have the first half covered there!

**Comment by lwaldsc** [comment]
On it.

**Comment by lwaldsc** [comment]
Ok, worked these up last night while drinking some wine on the porch, so if there are bits that need clarification, please let me know. These are not even a fraction of possible scenarios our patients go through but they're kind of the first themes to come to mind.

Common: Regina calls us at 6 weeks LMP on 3-12. We call her back and reach the patient. We explain DCAF’s policies of only funding after 7 weeks LMP. Regina’s options are to either schedule her appointment a week from the day she calls or fund her procedure on her own. We offer her references to clinics who will be able to see her and the number to other funders who may be able to help her. We emphasize although we cannot fund her now financially, we can in the future and she should call us back if that is the case. She says she will make an appointment for two weeks out. Regina calls us back on 3-20. **Her funding is completed. We send the pledge to the clinic on Regina's behalf. Regina goes to her appointment on 3-24 and has her abortion. The clinic mails us back the completed pledge form on 4-15. DCAF checks the pledge against our system, completes an entry in our ledger, notes the completed pledge on Regina's file in DARIA (which then anon’s her data), writes a check to the clinic and mails the check it to the clinic.**

Common: Janis calls us on 6-17. We call her back and leave a voicemail. We try again at the end of the night, but do not reach her. Janis calls us back on 6-18. We return her call and leave a voicemail. Janis calls us back on 6-24. We return her call, but her voicemail is turned off. We do not hear from Janis again.

Common: Sharon calls us on 5-10. She tells us to not leave a voicemail or ID ourselves as DCAF if we call. We return her call, but a man answers the phone. On asking for her, he says she is not home but asks who is calling. We tell him we are her friend June and Sharon can just give us a call back whenever. Sharon calls us back on 5-13. We call her back and successfully reach her. Her case proceeds like a normal case and she is able to get her abortion.

Common: Karen calls us on 2-1. She is 16 weeks. She already has an appointment scheduled for two days from now, has called other funders and confirmed their pledges, and has asked her mother for some money but she is still $140 short. We can cover the difference and write a pledge for her. We send the pledge to the clinic. Karen successfully goes to her appointment and has her abortion. For some reason, the clinic does not send the pledge form back until 6-15. We check the pledge against our system, completes an entry in our ledger, notes the completed pledge on Karen's file in DARIA (which then anon’s her data), writes a check to the clinic and mails it check to the clinic.

Common: Aaron calls us on 8-14. He is 15 weeks along. We give references to clinics and other funders and emphasize Aaron needs to call us back. We hear from Aaron on 8-19. He has made an appointment for 8-25 but has not reached the National fund. We tell him to keep trying and keep fundraising and he should call us back in a few days. On 8-23, Aaron calls us back but has still not spoken to the National Fund. We send an email to our contacts at the National Fund who reach out to Aaron and keep in touch with the National Fund until they confirm they have spoken to him. We call Aaron back on 8-24 to confirm that he has spoken to the National Fund and confirm our pledge to him as well. We send the pledge to the clinic. On 8-27, Aaron calls us again. We return his call. He explains that when he went to his appointment, the ultrasound showed that he was actually 18 weeks along, which made the appointment price much higher than he could currently afford even with pledges from us and the National Fund. He has luckily already reached his National Fund case manager and  they have upped their pledge. We are able to up our pledge to meet his needs as well and send a new pledge to the clinic. Aaron is able to make his appointment successfully. The clinic sends the pledge back to DCAF and we record/pay like the process described above.

Rarer: Cady calls in on 10-3 and leaves a message. She is at 10 weeks. We call her back and reach the patient. We refer her to clinics and possible other funders and make sure she knows to call us back. She calls us back on 10-5 and leaves a message. We call her back and discuss her fundraising. She has not reached her fundraising goal, so we discuss her options, including more ideas to fundraise or finding a cheaper clinic. At the end of the call, we emphasize she needs to call us back to receive funding from DCAF. Life gets busy for Cady and we do not hear from her again until 12-15. She is now at 20 weeks and needs to change her clinic. We call her back, discuss her options and give her clinic referrals. She calls us back on 12-19. She confirms she has her fundraising goal minus our pledge. She apologizes for the delay and we talk about other social services she could reach out to and give references. We send the pledge to the clinic on Cady’s behalf using the pledge procedure outlined above.

Rarer: Grechen is 14 years old. We receive a call from her case manager on 5-25. We call her back, but her case manager is only available during business hours. We leave the case manager a message telling them we will call back in the morning. The next morning, we reach the case manager and discuss Grechen’s options. We give them references to clinics and other funders emphasize they should call back when Grechen has an appointment. We do not hear from Grechen’s case manager again.

**Note: The "we never heard from this person again" and "this person hustled and we pledge them" are pretty interchangeable. I'm sure there *are*  indicators of when a patient is going to drop off or not, but it's not necessarily apparent to a case manager when they're returning calls.**

**Comment by lwaldsc** [comment]
Turning these into Colin's cases: 

**patient who called and left a voicemail but who we haven't called back yet (minimal information case)**
 Janis calls us on 6-17. She thinks she is about 9 weeks along, gives her phone number, and says it's ok to leave a voicemail. We have not called her back yet.

**patient who's had a few live calls but hasn't had a pledge sent yet**
 Cady calls in on 10-3 and leaves a message. She is at 10 weeks. We call her back and reach the patient. We refer her to clinics and possible other funders and make sure she knows to call us back. She calls us back on 10-5 and leaves a message. We call her back and discuss her fundraising. She has not reached her fundraising goal, so we discuss her options, including more ideas to fundraise or finding a cheaper clinic. At the end of the call, we emphasize she needs to call us back to receive funding from DCAF. 

**patient with a sent pledge**
Karen calls us on 2-1. She is 16 weeks. She already has an appointment scheduled for two days from now, has called other funders and confirmed their pledges, and has asked her mother for some money but she is still $140 short. We can cover the difference and write a pledge for her. We send the pledge to the clinic. Karen successfully goes to her appointment and has her abortion.

**Comment by colinxfleming** [comment]
@lomky let me know if there's anything else you need toward this end! I think your original insight on  this is going to be really great in a lot of ways.

**Comment by lwaldsc** [comment]
Agreed. Mocking up stories doesn't take long, so if there are any more
scenarios you're interested in or want maybe some more extreme examples or
more mundane examples, let me know!

**Comment by colinxfleming** [comment]
Developer centric but test data that reflects reality is still clutch for understanding, so marking futuretech.

**Comment by colinxfleming** [comment]
I'm still kinda interested in doing this; I think it's also a good opportunity to clean up some of the bitrot in our seeds file. Going to mess around with this some in 5-10m increments over the next week.

**Comment by colinxfleming** [comment]
closing, gotta focus more on outward facing impact stuff for the time being, sorry
